### ISSUE TITLE
Typo

### ISSUE THREAD

**Issue by win32nipuh** [oleg-shilo/PropMan.VSIX#2]
There is
"Proerty Manipulation"

Regards,
Олег.

**Comment by oleg-shilo** [comment]
Hi Oleg,
Can you please indicate where this typo is located. I just cannot find it.

**Comment by win32nipuh** [comment]
Goto the link
https://github.com/oleg-shilo/PropMan.VSIX
and the title
"Proerty Manipulation Utilities for encapsulating fields, converting auto-properties to full properties and back."

**Comment by oleg-shilo** [comment]
:)
Txs. I though you were referring to th typo in the code.

Fixed now.
